"""Logical catalog fixture for tests (mirrors the pre-remote-only in-repo
catalog). Tests patch the remote registry to serve from this."""

from __future__ import annotations

from typing import Any

_QWEN_TTS_BACKENDS = {
    "preferred": [
        {
            "name": "faster-qwen3-tts",
            "requires": {
                "python_modules": ["torch", "faster_qwen3_tts"],
                "accelerators": ["cuda"],
                "min_versions": {"torch": "2.5.1"},
            },
        }
    ],
    "fallback": {
        "name": "qwen-tts",
        "requires": {"python_modules": ["torch"]},
    },
}




FIXTURE_CATALOG: dict[str, dict[str, dict[str, Any]]] = {
    "parakeet-stt": {
        "tdt-0.6b": {
            "type": "stt",
            "description": "NVIDIA Parakeet TDT 0.6B — top Open ASR Leaderboard model",
            "license": "CC-BY-4.0",
            "parameters": {"sample_rate": 16000},
            "variants": [
                {
                    "id": "onnx",
                    "aliases": ["cpu"],
                    "priority": 0,
                    "fallback": True,
                    "requires": {"python_modules": ["onnxruntime"]},
                    "source": "istupakov/parakeet-tdt-0.6b-v2-onnx",
                    "runtime_source": "nvidia/parakeet-tdt-0.6b-v2",
                    "architecture": "parakeet",
                    "adapter": "parakeet-stt-onnx",
                    "format": "onnx",
                    "files": [
                        "config.json",
                        "decoder_joint-model.onnx",
                        "encoder-model.onnx",
                        "encoder-model.onnx.data",
                        "nemo128.onnx",
                        "vocab.txt",
                    ],
                    "adapter_package": "vox-parakeet",
                },
            ],
        },
        "tdt-0.6b-v3": {
            "type": "stt",
            "description": "NVIDIA Parakeet TDT 0.6B v3 — 25 languages, streaming support",
            "license": "CC-BY-4.0",
            "parameters": {"sample_rate": 16000},
            "variants": [
                {
                    "id": "nemo",
                    "aliases": ["cuda"],
                    "priority": 100,
                    "requires": {"python_modules": ["torch"], "accelerators": ["cuda"]},
                    "source": "nvidia/parakeet-tdt-0.6b-v3",
                    "architecture": "parakeet-nemo",
                    "adapter": "parakeet-stt-nemo",
                    "format": "pytorch",
                    "files": ["parakeet-tdt-0.6b-v3.nemo"],
                    "adapter_package": "vox-parakeet",
                },
                {
                    "id": "onnx",
                    "aliases": ["cpu"],
                    "priority": 0,
                    "fallback": True,
                    "requires": {"python_modules": ["onnxruntime"]},
                    "source": "istupakov/parakeet-tdt-0.6b-v3-onnx",
                    "runtime_source": "nvidia/parakeet-tdt-0.6b-v3",
                    "architecture": "parakeet",
                    "adapter": "parakeet-stt-onnx",
                    "format": "onnx",
                    "files": [
                        "config.json",
                        "decoder_joint-model.onnx",
                        "encoder-model.onnx",
                        "encoder-model.onnx.data",
                        "nemo128.onnx",
                        "vocab.txt",
                    ],
                    "adapter_package": "vox-parakeet",
                },
            ],
        },
        "tdt-1.1b": {
            "type": "stt",
            "description": "NVIDIA Parakeet TDT 1.1B — larger native NeMo/PyTorch CUDA ASR",
            "license": "CC-BY-4.0",
            "parameters": {"sample_rate": 16000},
            "variants": [
                {
                    "id": "nemo",
                    "aliases": ["cuda"],
                    "priority": 100,
                    "fallback": True,
                    "requires": {"python_modules": ["torch"], "accelerators": ["cuda"]},
                    "source": "nvidia/parakeet-tdt-1.1b",
                    "architecture": "parakeet-nemo",
                    "adapter": "parakeet-stt-nemo",
                    "format": "pytorch",
                    "files": ["parakeet-tdt-1.1b.nemo"],
                    "adapter_package": "vox-parakeet",
                },
            ],
        },
    },
    "kokoro-tts": {
        "v1.0": {
            "architecture": "kokoro",
            "type": "tts",
            "description": "Kokoro 82M — hardware-aware TTS selection",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "default_voice": "af_heart"},
            "variants": [
                {
                    "id": "torch",
                    "aliases": ["cuda"],
                    "priority": 100,
                    "requires": {
                        "python_modules": ["torch"],
                        "accelerators": ["cuda"],
                    },
                    "source": "hexgrad/Kokoro-82M",
                    "architecture": "kokoro-torch",
                    "adapter": "kokoro-tts-torch",
                    "format": "pytorch",
                    "files": ["kokoro-v1_0.pth"],
                    "adapter_package": "vox-kokoro",
                },
                {
                    "id": "onnx",
                    "aliases": ["cpu"],
                    "priority": 0,
                    "fallback": True,
                    "requires": {"python_modules": ["onnxruntime"]},
                    "source": "onnx-community/Kokoro-82M-v1.0-ONNX",
                    "architecture": "kokoro",
                    "adapter": "kokoro-tts-onnx",
                    "format": "onnx",
                    "adapter_package": "vox-kokoro",
                },
            ],
        },
    },
    "xtts-tts": {
        "v2": {
            "source": "coqui/XTTS-v2",
            "architecture": "xtts-v2",
            "type": "tts",
            "adapter": "xtts-tts-torch",
            "format": "pytorch",
            "description": "Coqui XTTS-v2 — multilingual voice cloning TTS",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-xtts",
        },
    },
    "whisper-stt": {
        "large-v3": {
            "source": "Systran/faster-whisper-large-v3",
            "architecture": "whisper",
            "type": "stt",
            "adapter": "whisper-stt-ct2",
            "format": "ct2",
            "description": "OpenAI Whisper Large V3 via CTranslate2",
            "license": "MIT",
            "parameters": {"sample_rate": 16000, "beam_size": 5},
            "adapter_package": "vox-whisper",
        },
        "large-v3-turbo": {
            "source": "deepdml/faster-whisper-large-v3-turbo-ct2",
            "architecture": "whisper",
            "type": "stt",
            "adapter": "whisper-stt-ct2",
            "format": "ct2",
            "description": "OpenAI Whisper Large V3 Turbo — faster with minor quality loss",
            "license": "MIT",
            "parameters": {"sample_rate": 16000, "beam_size": 5},
            "adapter_package": "vox-whisper",
        },
        "base.en": {
            "source": "Systran/faster-whisper-base.en",
            "architecture": "whisper",
            "type": "stt",
            "adapter": "whisper-stt-ct2",
            "format": "ct2",
            "description": "OpenAI Whisper Base English — small and fast",
            "license": "MIT",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-whisper",
        },
        "small.en": {
            "source": "Systran/faster-whisper-small.en",
            "architecture": "whisper",
            "type": "stt",
            "adapter": "whisper-stt-ct2",
            "format": "ct2",
            "description": "OpenAI Whisper Small English — stronger English transcription than base.en",
            "license": "MIT",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-whisper",
        },
        "medium.en": {
            "source": "Systran/faster-whisper-medium.en",
            "architecture": "whisper",
            "type": "stt",
            "adapter": "whisper-stt-ct2",
            "format": "ct2",
            "description": "OpenAI Whisper Medium English — larger English CTranslate2 checkpoint",
            "license": "MIT",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-whisper",
        },
    },
    "piper-tts": {
        "en-us-lessac-medium": {
            "source": "rhasspy/piper-voices",
            "architecture": "piper",
            "type": "tts",
            "adapter": "piper-tts-onnx",
            "format": "onnx",
            "description": "Piper English US Lessac Medium — single-voice ONNX TTS",
            "license": "MIT",
            "parameters": {"sample_rate": 22050},
            "files": [
                "en/en_US/lessac/medium/en_US-lessac-medium.onnx",
                "en/en_US/lessac/medium/en_US-lessac-medium.onnx.json",
            ],
            "adapter_package": "vox-piper",
        },
    },
    "chatterbox-tts-turbo": {
        "0.1.7": {
            "architecture": "chatterbox-turbo",
            "type": "tts",
            "description": "Resemble Chatterbox Turbo — fast neural TTS with voice cloning",
            "license": "MIT",
            "parameters": {"sample_rate": 24000},
            "variants": [
                {
                    "id": "torch",
                    "aliases": ["cuda"],
                    "priority": 100,
                    "source": "ResembleAI/chatterbox-turbo",
                    "adapter": "chatterbox-tts-turbo",
                    "format": "pytorch",
                    "requires": {"python_modules": ["torch"]},
                    "adapter_package": "vox-chatterbox",
                },
                {
                    "id": "onnx",
                    "aliases": ["cpu"],
                    "priority": 0,
                    "fallback": True,
                    "source": "ResembleAI/chatterbox-turbo-ONNX",
                    "adapter": "chatterbox-tts-turbo-onnx",
                    "format": "onnx",
                    "parameters": {"sample_rate": 24000, "onnx_dtype": "fp32"},
                    "requires": {"python_modules": ["onnxruntime"]},
                    "files": [
                        "config.json",
                        "generation_config.json",
                        "preprocessor_config.json",
                        "tokenizer.json",
                        "tokenizer_config.json",
                        "onnx/conditional_decoder.onnx",
                        "onnx/conditional_decoder.onnx_data",
                        "onnx/embed_tokens.onnx",
                        "onnx/embed_tokens.onnx_data",
                        "onnx/language_model.onnx",
                        "onnx/language_model.onnx_data",
                        "onnx/speech_encoder.onnx",
                        "onnx/speech_encoder.onnx_data",
                    ],
                    "adapter_package": "vox-chatterbox",
                },
            ],
        },
    },
    "chatterbox-tts": {
        "0.1.7": {
            "source": "ResembleAI/chatterbox",
            "architecture": "chatterbox",
            "type": "tts",
            "adapter": "chatterbox-tts",
            "format": "pytorch",
            "description": "Resemble Chatterbox — expressive neural TTS with voice cloning",
            "license": "MIT",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-chatterbox",
        },
    },
    "chatterbox-tts-multilingual": {
        "0.1.7": {
            "source": "ResembleAI/chatterbox",
            "architecture": "chatterbox-multilingual",
            "type": "tts",
            "adapter": "chatterbox-tts-multilingual",
            "format": "pytorch",
            "description": "Resemble Chatterbox Multilingual — multilingual voice cloning TTS",
            "license": "MIT",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-chatterbox",
        },
    },
    "cosyvoice2-tts": {
        "0.5b": {
            "source": "FunAudioLLM/CosyVoice2-0.5B",
            "architecture": "cosyvoice2",
            "type": "tts",
            "adapter": "cosyvoice2-tts-torch",
            "format": "pytorch",
            "description": "CosyVoice 2 0.5B — streaming zero-shot TTS for interactive voice agents",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-cosyvoice",
        },
    },
    "orpheus-tts": {
        "medium-3b": {
            "source": "canopylabs/orpheus-tts-0.1-finetune-prod",
            "architecture": "orpheus",
            "type": "tts",
            "adapter": "orpheus-tts-vllm",
            "format": "pytorch",
            "description": "Orpheus medium 3B — expressive vLLM-backed streaming TTS",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "default_voice": "tara"},
            "adapter_package": "vox-orpheus",
        },
    },
    "indextts-tts": {
        "2": {
            "source": "IndexTeam/IndexTTS-2",
            "architecture": "indextts2",
            "type": "tts",
            "adapter": "indextts-tts-torch",
            "format": "pytorch",
            "description": "IndexTTS2 — zero-shot voice cloning TTS",
            "license": "other",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-indextts",
        },
    },
    "spark-tts": {
        "0.5b": {
            "source": "SparkAudio/Spark-TTS-0.5B",
            "architecture": "spark-tts",
            "type": "tts",
            "adapter": "spark-tts-torch",
            "format": "pytorch",
            "description": "Spark-TTS 0.5B — efficient LLM-based voice cloning TTS",
            "license": "cc-by-nc-sa-4.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-spark",
        },
    },
    "neutts-air-tts": {
        "air": {
            "source": "neuphonic/neutts-air",
            "architecture": "neutts-air",
            "type": "tts",
            "adapter": "neutts-air-tts-torch",
            "format": "pytorch",
            "description": "NeuTTS Air — compact voice cloning TTS",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-neutts",
        },
    },
    "dia-tts": {
        "1.6b": {
            "source": "nari-labs/Dia-1.6B-0626",
            "architecture": "dia",
            "type": "tts",
            "adapter": "dia-tts-torch",
            "format": "pytorch",
            "description": "Dia 1.6B (0626) — multi-speaker dialogue TTS with non-verbal sounds",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 44000},
            "adapter_package": "vox-dia",
        },
    },
    "sesame-tts": {
        "csm-1b": {
            "source": "sesame/csm-1b",
            "architecture": "sesame",
            "type": "tts",
            "adapter": "sesame-tts-torch",
            "format": "pytorch",
            "description": "Sesame CSM 1B — context-aware conversational speech model",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "default_voice": "0"},
            "adapter_package": "vox-sesame",
        },
    },
    "openvoice-tts": {
        "v1": {
            "source": "myshell-ai/OpenVoice",
            "architecture": "openvoice",
            "type": "tts",
            "adapter": "openvoice-tts-torch",
            "format": "pytorch",
            "description": "MyShell OpenVoice V1 — instant voice cloning and style control",
            "license": "MIT",
            "parameters": {"sample_rate": 22050, "default_voice": "en/default"},
            "files": [
                "checkpoints/base_speakers/EN/checkpoint.pth",
                "checkpoints/base_speakers/EN/config.json",
                "checkpoints/base_speakers/EN/en_default_se.pth",
                "checkpoints/base_speakers/EN/en_style_se.pth",
                "checkpoints/base_speakers/ZH/checkpoint.pth",
                "checkpoints/base_speakers/ZH/config.json",
                "checkpoints/base_speakers/ZH/zh_default_se.pth",
                "checkpoints/converter/checkpoint.pth",
                "checkpoints/converter/config.json",
            ],
            "adapter_package": "vox-openvoice",
        },
    },
    "voxtral-stt": {
        "mini-3b": {
            "source": "mistralai/Voxtral-Mini-3B-2507",
            "architecture": "voxtral-mini",
            "type": "stt",
            "adapter": "voxtral-stt-torch",
            "format": "pytorch",
            "description": "Mistral Voxtral Mini 3B — audio understanding and transcription",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-voxtral",
        },
        "small-24b": {
            "source": "mistralai/Voxtral-Small-24B-2507",
            "architecture": "voxtral-small",
            "type": "stt",
            "adapter": "voxtral-stt-torch",
            "format": "pytorch",
            "description": "Mistral Voxtral Small 24B — high-quality audio understanding and transcription",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-voxtral",
        },
        "24b": {
            "source": "mistralai/Voxtral-Small-24B-2507",
            "architecture": "voxtral-small",
            "type": "stt",
            "adapter": "voxtral-stt-torch",
            "format": "pytorch",
            "description": "Mistral Voxtral 24B — size alias for the larger Small 24B transcription model",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-voxtral",
        },
        "realtime-4b": {
            "source": "mistralai/Voxtral-Mini-4B-Realtime-2602",
            "architecture": "voxtral-realtime",
            "type": "stt",
            "adapter": "voxtral-stt-torch",
            "format": "pytorch",
            "description": "Mistral Voxtral Realtime 4B — sub-500ms latency transcription, 13 languages",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-voxtral",
        },
    },
    "voxtral-tts": {
        "4b": {
            "source": "mistralai/Voxtral-4B-TTS-2603",
            "architecture": "voxtral-tts",
            "type": "tts",
            "adapter": "voxtral-tts-vllm",
            "format": "pytorch",
            "description": "Mistral Voxtral TTS 4B — preset-voice TTS, 9 languages, ~90ms TTFA",
            "license": "CC-BY-NC-4.0",
            "parameters": {"sample_rate": 24000, "default_voice": "neutral_female"},
            "adapter_package": "vox-voxtral",
        },
    },
    "speecht5-tts": {
        "base": {
            "source": "microsoft/speecht5_tts",
            "architecture": "speecht5-tts",
            "type": "tts",
            "adapter": "speecht5-tts-torch",
            "format": "pytorch",
            "description": "Microsoft SpeechT5 TTS — lightweight text-to-speech with speaker embeddings",
            "license": "MIT",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-microsoft",
        },
    },
    "speecht5-stt": {
        "base": {
            "source": "microsoft/speecht5_asr",
            "architecture": "speecht5-asr",
            "type": "stt",
            "adapter": "speecht5-stt-torch",
            "format": "pytorch",
            "description": "Microsoft SpeechT5 ASR — lightweight speech recognition",
            "license": "MIT",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-microsoft",
        },
    },
    "vibevoice-tts": {
        "realtime-0.5b": {
            "source": "microsoft/VibeVoice-Realtime-0.5B",
            "architecture": "vibevoice-realtime",
            "type": "tts",
            "adapter": "vibevoice-tts-torch",
            "format": "pytorch",
            "description": "Microsoft VibeVoice Realtime 0.5B — ~300ms streaming TTS",
            "license": "MIT",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-microsoft",
        },
        "1.5b": {
            "source": "microsoft/VibeVoice-1.5B",
            "architecture": "vibevoice",
            "type": "tts",
            "adapter": "vibevoice-tts-torch",
            "format": "pytorch",
            "description": "Microsoft VibeVoice 1.5B — high-quality TTS with 64K token context",
            "license": "MIT",
            "parameters": {"sample_rate": 24000},
            "adapter_package": "vox-microsoft",
        },
    },
    "qwen3-stt": {
        "1.7b": {
            "source": "Qwen/Qwen3-ASR-1.7B",
            "architecture": "qwen3-asr",
            "type": "stt",
            "adapter": "qwen3-stt-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-ASR 1.7B — 52 languages, word timestamps",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-qwen",
        },
        "0.6b": {
            "source": "Qwen/Qwen3-ASR-0.6B",
            "architecture": "qwen3-asr",
            "type": "stt",
            "adapter": "qwen3-stt-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-ASR 0.6B — lightweight 52-language speech recognition",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 16000},
            "adapter_package": "vox-qwen",
        },
    },
    "qwen3-tts": {
        "1.7b": {
            "source": "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
            "architecture": "qwen3-tts",
            "type": "tts",
            "adapter": "qwen3-tts-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-TTS 1.7B — multilingual speaker-based CustomVoice TTS with streaming",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "default_voice": "Ryan"},
            "adapter_package": "vox-qwen",
            "backends": _QWEN_TTS_BACKENDS,
        },
        "0.6b": {
            "source": "Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice",
            "architecture": "qwen3-tts",
            "type": "tts",
            "adapter": "qwen3-tts-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-TTS 0.6B — lightweight multilingual speaker-based CustomVoice TTS",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "default_voice": "Ryan"},
            "adapter_package": "vox-qwen",
            "backends": _QWEN_TTS_BACKENDS,
        },
        "1.7b-clone": {
            "source": "Qwen/Qwen3-TTS-12Hz-1.7B-Base",
            "architecture": "qwen3-tts",
            "type": "tts",
            "adapter": "qwen3-tts-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-TTS 1.7B Base — zero-shot voice cloning from reference audio",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "mode": "clone"},
            "adapter_package": "vox-qwen",
            "backends": _QWEN_TTS_BACKENDS,
        },
        "0.6b-clone": {
            "source": "Qwen/Qwen3-TTS-12Hz-0.6B-Base",
            "architecture": "qwen3-tts",
            "type": "tts",
            "adapter": "qwen3-tts-torch",
            "format": "pytorch",
            "description": "Alibaba Qwen3-TTS 0.6B Base — lightweight zero-shot voice cloning from reference audio",
            "license": "Apache-2.0",
            "parameters": {"sample_rate": 24000, "mode": "clone"},
            "adapter_package": "vox-qwen",
            "backends": _QWEN_TTS_BACKENDS,
        },
    },
}
