from vox.operations.errors import (
    AdapterInstallError,
    CatalogEntryNotFoundError,
    EmptyAudioError,
    EmptyInputError,
    ModelInUseError,
    NoAudioGeneratedError,
    NoDefaultModelError,
    OperationError,
    StoredModelNotFoundError,
    VoiceAudioRequiredError,
    VoiceIdRequiredError,
    VoiceNameRequiredError,
    VoiceNotFoundOperationError,
    VoiceReferenceNotFoundError,
    WrongModelTypeError,
)

__all__ = [
    "AdapterInstallError",
    "CatalogEntryNotFoundError",
    "EmptyAudioError",
    "EmptyInputError",
    "ModelInUseError",
    "NoAudioGeneratedError",
    "NoDefaultModelError",
    "OperationError",
    "StoredModelNotFoundError",
    "VoiceAudioRequiredError",
    "VoiceIdRequiredError",
    "VoiceNameRequiredError",
    "VoiceNotFoundOperationError",
    "VoiceReferenceNotFoundError",
    "WrongModelTypeError",
]
